### ISSUE TITLE
QGA-1 Create user model

### ISSUE THREAD

**Issue by Gruseckis** [Gruseckis/quiz-game-api#2]
Create mongoose model for user.
User should have: 

- username | string
- email*^ | string
- hashedPassword* | string($password)
- name* | string
- surname* | string
- dateOfBirth* | string($date)
- level | string Enum:[ 'user', 'quizer', 'moderator', 'admin' ]

should have a time stamp
 * fields are required. ^ email should be unique

User Model should have following methods:
should have a pre hook to has a password.
- save() - should save model to database
- comparePassword() - should compare supplied password with password from DB
- getAllUsers() - should retrieve all user and return them.
- getUserByEmail() - should get user by email.
- getUserById() - should get user by Id.
- updateUserById() - should update user information.
- deleteUserById() - should delete user.

**Comment by nondante** [comment]
Created
