### ISSUE TITLE
QGA-4 Create result model

### ISSUE THREAD

**Issue by Gruseckis** [Gruseckis/quiz-game-api#5]
Description:  A collection of answers for a specific quiz for a specific response, (one attempt per quiz per person)

Result model should have:
- id | string | ID of a result
- recordIds | Array [List of all the records in order of them being answered]
- userId | string ID of a user who was filling in this response
- quizId | stringID  of the quiz that user was filling in 

Result model should have these methods:
- save() - save to DB
- getAllResults() - gets all results
- getResultById() - get result by id
- getAllResultByUserId() - get all results of a given user
- getAllresultsByQuizId() - get all results for a given quiz
- updateResultById() - update results by Id
- deleteResultById() - delete result by id

* only admin and moderator can remove and update results.

**Comment by hazedelia** [comment]
DONE
